[workspace]
members = ["crates/aec-rs-sys"]

[package]
name = "aec-rs"
version = "0.1.0"
edition = "2021"
authors = ["thewh1teagle"]
homepage = "https://github.com/thewh1teagle/aec-rs"

[dependencies]
aec-rs-sys = { path = "crates/aec-rs-sys", version = "0.1.0" }

[dev-dependencies]
hound = { version = "3.5.1" }
