[package]
name = "libaec"
version = "0.1.0"
edition = "2021"

[dependencies]
aec-rs = { path = "../../", version = "0.1.0" }

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.26.0"
